# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jake/PhD/Edge_Disjoint/c++/Lagrangian_Relax/git

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jake/PhD/Edge_Disjoint/c++/Lagrangian_Relax/git

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jake/PhD/Edge_Disjoint/c++/Lagrangian_Relax/git/CMakeFiles /home/jake/PhD/Edge_Disjoint/c++/Lagrangian_Relax/git/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jake/PhD/Edge_Disjoint/c++/Lagrangian_Relax/git/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main_test

# Build rule for target.
main_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_test
.PHONY : main_test

# fast build rule for target.
main_test/fast:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/build
.PHONY : main_test/fast

src/ArgParser.o: src/ArgParser.cpp.o

.PHONY : src/ArgParser.o

# target to build an object file
src/ArgParser.cpp.o:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/ArgParser.cpp.o
.PHONY : src/ArgParser.cpp.o

src/ArgParser.i: src/ArgParser.cpp.i

.PHONY : src/ArgParser.i

# target to preprocess a source file
src/ArgParser.cpp.i:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/ArgParser.cpp.i
.PHONY : src/ArgParser.cpp.i

src/ArgParser.s: src/ArgParser.cpp.s

.PHONY : src/ArgParser.s

# target to generate assembly for a file
src/ArgParser.cpp.s:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/ArgParser.cpp.s
.PHONY : src/ArgParser.cpp.s

src/CpuTimer.o: src/CpuTimer.cpp.o

.PHONY : src/CpuTimer.o

# target to build an object file
src/CpuTimer.cpp.o:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/CpuTimer.cpp.o
.PHONY : src/CpuTimer.cpp.o

src/CpuTimer.i: src/CpuTimer.cpp.i

.PHONY : src/CpuTimer.i

# target to preprocess a source file
src/CpuTimer.cpp.i:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/CpuTimer.cpp.i
.PHONY : src/CpuTimer.cpp.i

src/CpuTimer.s: src/CpuTimer.cpp.s

.PHONY : src/CpuTimer.s

# target to generate assembly for a file
src/CpuTimer.cpp.s:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/CpuTimer.cpp.s
.PHONY : src/CpuTimer.cpp.s

src/ED.o: src/ED.cpp.o

.PHONY : src/ED.o

# target to build an object file
src/ED.cpp.o:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/ED.cpp.o
.PHONY : src/ED.cpp.o

src/ED.i: src/ED.cpp.i

.PHONY : src/ED.i

# target to preprocess a source file
src/ED.cpp.i:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/ED.cpp.i
.PHONY : src/ED.cpp.i

src/ED.s: src/ED.cpp.s

.PHONY : src/ED.s

# target to generate assembly for a file
src/ED.cpp.s:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/ED.cpp.s
.PHONY : src/ED.cpp.s

src/LaPSO.o: src/LaPSO.cpp.o

.PHONY : src/LaPSO.o

# target to build an object file
src/LaPSO.cpp.o:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/LaPSO.cpp.o
.PHONY : src/LaPSO.cpp.o

src/LaPSO.i: src/LaPSO.cpp.i

.PHONY : src/LaPSO.i

# target to preprocess a source file
src/LaPSO.cpp.i:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/LaPSO.cpp.i
.PHONY : src/LaPSO.cpp.i

src/LaPSO.s: src/LaPSO.cpp.s

.PHONY : src/LaPSO.s

# target to generate assembly for a file
src/LaPSO.cpp.s:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/LaPSO.cpp.s
.PHONY : src/LaPSO.cpp.s

src/VolVolume.o: src/VolVolume.cpp.o

.PHONY : src/VolVolume.o

# target to build an object file
src/VolVolume.cpp.o:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/VolVolume.cpp.o
.PHONY : src/VolVolume.cpp.o

src/VolVolume.i: src/VolVolume.cpp.i

.PHONY : src/VolVolume.i

# target to preprocess a source file
src/VolVolume.cpp.i:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/VolVolume.cpp.i
.PHONY : src/VolVolume.cpp.i

src/VolVolume.s: src/VolVolume.cpp.s

.PHONY : src/VolVolume.s

# target to generate assembly for a file
src/VolVolume.cpp.s:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/VolVolume.cpp.s
.PHONY : src/VolVolume.cpp.s

src/anyoption.o: src/anyoption.cpp.o

.PHONY : src/anyoption.o

# target to build an object file
src/anyoption.cpp.o:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/anyoption.cpp.o
.PHONY : src/anyoption.cpp.o

src/anyoption.i: src/anyoption.cpp.i

.PHONY : src/anyoption.i

# target to preprocess a source file
src/anyoption.cpp.i:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/anyoption.cpp.i
.PHONY : src/anyoption.cpp.i

src/anyoption.s: src/anyoption.cpp.s

.PHONY : src/anyoption.s

# target to generate assembly for a file
src/anyoption.cpp.s:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/anyoption.cpp.s
.PHONY : src/anyoption.cpp.s

src/djikstra.o: src/djikstra.cpp.o

.PHONY : src/djikstra.o

# target to build an object file
src/djikstra.cpp.o:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/djikstra.cpp.o
.PHONY : src/djikstra.cpp.o

src/djikstra.i: src/djikstra.cpp.i

.PHONY : src/djikstra.i

# target to preprocess a source file
src/djikstra.cpp.i:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/djikstra.cpp.i
.PHONY : src/djikstra.cpp.i

src/djikstra.s: src/djikstra.cpp.s

.PHONY : src/djikstra.s

# target to generate assembly for a file
src/djikstra.cpp.s:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/djikstra.cpp.s
.PHONY : src/djikstra.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/prep_mip.o: src/prep_mip.cpp.o

.PHONY : src/prep_mip.o

# target to build an object file
src/prep_mip.cpp.o:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/prep_mip.cpp.o
.PHONY : src/prep_mip.cpp.o

src/prep_mip.i: src/prep_mip.cpp.i

.PHONY : src/prep_mip.i

# target to preprocess a source file
src/prep_mip.cpp.i:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/prep_mip.cpp.i
.PHONY : src/prep_mip.cpp.i

src/prep_mip.s: src/prep_mip.cpp.s

.PHONY : src/prep_mip.s

# target to generate assembly for a file
src/prep_mip.cpp.s:
	$(MAKE) -f CMakeFiles/main_test.dir/build.make CMakeFiles/main_test.dir/src/prep_mip.cpp.s
.PHONY : src/prep_mip.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main_test"
	@echo "... src/ArgParser.o"
	@echo "... src/ArgParser.i"
	@echo "... src/ArgParser.s"
	@echo "... src/CpuTimer.o"
	@echo "... src/CpuTimer.i"
	@echo "... src/CpuTimer.s"
	@echo "... src/ED.o"
	@echo "... src/ED.i"
	@echo "... src/ED.s"
	@echo "... src/LaPSO.o"
	@echo "... src/LaPSO.i"
	@echo "... src/LaPSO.s"
	@echo "... src/VolVolume.o"
	@echo "... src/VolVolume.i"
	@echo "... src/VolVolume.s"
	@echo "... src/anyoption.o"
	@echo "... src/anyoption.i"
	@echo "... src/anyoption.s"
	@echo "... src/djikstra.o"
	@echo "... src/djikstra.i"
	@echo "... src/djikstra.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/prep_mip.o"
	@echo "... src/prep_mip.i"
	@echo "... src/prep_mip.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

